# automatic run setup
#   $ pre-commit install
#
# manual
#   $ pre-commit run -a

# use default options for ci
ci:
  autoupdate_schedule: "monthly"
  submodules: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
    exclude: 'perftests/results/.*\.txt$'
  - id: check-case-conflict
    exclude: 'perftests/results/.*\.txt$'
  - id: check-docstring-first
    exclude: 'perftests/results/.*\.txt$'
  - id: check-merge-conflict
    exclude: 'perftests/results/.*\.txt$'
  - id: check-symlinks
    exclude: 'perftests/results/.*\.txt$'
  - id: check-toml
    exclude: 'perftests/results/.*\.txt$'
  - id: check-yaml
    exclude: 'perftests/results/.*\.txt$'
  - id: debug-statements
    exclude: 'perftests/results/.*\.txt$'
  - id: end-of-file-fixer
    exclude: 'perftests/results/.*\.txt$'
  - id: mixed-line-ending
    exclude: 'perftests/results/.*\.txt$'
  - id: requirements-txt-fixer
    exclude: 'perftests/results/.*\.txt$'
  - id: trailing-whitespace
    exclude: 'perftests/results/.*\.txt$'

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.4.0"
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/PyCQA/isort
  rev: "5.12.0"
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: "23.3.0"
  hooks:
  - id: black
    args: [--line-length=79]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--extend-ignore=E203]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c,c++,cuda]
